# Generated by Django 4.2.5 on 2024-01-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='extraservice',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='minutsms',
        ),
        migrations.AddField(
            model_name='service',
            name='mobicinema',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='packet',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='rouming',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tariff',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ussd',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='unlim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.unlim'),
            preserve_default=False,
        ),
    ]
