# Generated by Django 4.2.5 on 2024-01-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tariffs_rename_tariff_mytariff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='packet',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='main.packet'),
            preserve_default=False,
        ),
    ]
