# Generated by Django 4.2.5 on 2024-01-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_packet_service_packet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='MyTariff',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packet',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tariffs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unlim',
        ),
        migrations.DeleteModel(
            name='Packet',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Tariffs',
        ),
        migrations.DeleteModel(
            name='Unlim',
        ),
    ]
