# Generated by Django 4.2.5 on 2024-01-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bonus_mytariff_packet_tariffs_unlim_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='minutsms',
            field=models.BooleanField(default=False),
        ),
    ]
