# Generated by Django 4.2.5 on 2024-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_bonus_minutsms_mytariff_packet_tariffs_unlim_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='minutsms',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packet',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tariffs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unlim',
        ),
        migrations.AddField(
            model_name='service',
            name='minutsms',
            field=models.ManyToManyField(to='main.minutsms'),
        ),
        migrations.AddField(
            model_name='service',
            name='packet',
            field=models.ManyToManyField(to='main.packet'),
        ),
        migrations.AddField(
            model_name='service',
            name='tariffs',
            field=models.ManyToManyField(to='main.tariffs'),
        ),
        migrations.AddField(
            model_name='service',
            name='unlim',
            field=models.ManyToManyField(to='main.unlim'),
        ),
    ]
