# Generated by Django 4.2.5 on 2024-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_service_minutsms_remove_service_packet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='extraservice',
            field=models.ManyToManyField(to='main.extraservice'),
        ),
    ]
