# Generated by Django 4.2.5 on 2024-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_extraservice_service_extraservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rouming',
            field=models.BooleanField(default=False),
        ),
    ]
