# Generated by Django 4.2.5 on 2024-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_service_rouming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ussd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='ussd',
            field=models.ManyToManyField(to='main.ussd'),
        ),
    ]
