# Generated by Django 4.2.5 on 2024-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_ussd_service_ussd'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mobicinema',
            field=models.BooleanField(default=False),
        ),
    ]
