# Generated by Django 4.2.5 on 2024-01-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_servicetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='MyTariff',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='Recomendate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='extraservice',
        ),
        migrations.RemoveField(
            model_name='service',
            name='minutsms',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packet',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tariffs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unlim',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ussd',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='ExtraService',
        ),
        migrations.DeleteModel(
            name='MinutSms',
        ),
        migrations.DeleteModel(
            name='Packet',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Tariffs',
        ),
        migrations.DeleteModel(
            name='Unlim',
        ),
        migrations.DeleteModel(
            name='Ussd',
        ),
    ]
